import { Router } from 'express'
import { randomUUID } from 'node:crypto'
import type { DataReport, ReportCreationAndUpdateRequest, ReportTask, DataComponent } from '@webapp-types/report'
import type { PageQueryParams } from '@webapp-types/page'
import { db } from '../db.js'
import { paginate } from '../paginate.js'
import { buildPdf } from '../pdfFactory.js'

export const reportsRouter = Router()

const numberOrUndefined = (v: unknown): number | undefined => {
  if (v == null) return undefined
  const n = Number(v)

  return Number.isFinite(n) ? n : undefined
}

const toPageQuery = (q: Record<string, unknown>): PageQueryParams => ({
  filter: typeof q.filter === 'string' ? q.filter : undefined,
  sort: typeof q.sort === 'string' ? q.sort : undefined,
  page: numberOrUndefined(q.page),
  size: numberOrUndefined(q.size),
})

const resolveComponents = (request: ReportCreationAndUpdateRequest): DataComponent[] => {
  return (request.dataComponents ?? []).map((dc) => ({
    type: dc.type,
    datas: dc.dataSeriesReferences
      .map((ref) => db.dataSeries.get(ref))
      .filter((d): d is NonNullable<typeof d> => !!d),
  }))
}

reportsRouter.get('/', (req, res) => {
  const page = paginate(Array.from(db.reports.values()), toPageQuery(req.query), {
    filterFields: ['displayName', 'reference', 'creator'],
  })
  res.json(page)
})

reportsRouter.post('/', (req, res) => {
  const body = req.body as ReportCreationAndUpdateRequest
  const reference = `report-${Date.now()}`
  const nowIso = new Date().toISOString()
  const created: DataReport = {
    reference,
    version: nowIso,
    creator: 'qalipsis-dev',
    displayName: body.displayName,
    description: body.description,
    sharingMode: body.sharingMode ?? 'NONE',
    campaignKeys: body.campaignKeys,
    campaignNamesPatterns: body.campaignNamesPatterns,
    scenarioNamesPatterns: body.scenarioNamesPatterns,
    resolvedCampaigns: (body.campaignKeys ?? [])
      .map((k) => db.campaigns.get(k))
      .filter((c): c is NonNullable<typeof c> => !!c)
      .map((c) => ({ key: c.key, name: c.name })),
    resolvedScenarioNames: db.scenarios.map((s) => s.name),
    dataComponents: resolveComponents(body),
  }
  db.reports.set(reference, created)
  res.json(created)
})

// PDF download — must come BEFORE /:reference so it isn't matched by it
reportsRouter.get('/file/:taskRef', async (req, res) => {
  const task = db.reportTasks.get(req.params.taskRef)
  if (!task) {
    res.status(404).end()

    return
  }
  if (Date.now() < task.readyAt) {
    res.status(404).end()

    return
  }
  if (!task.payload) {
    const report = db.reports.get(task.reportReference)
    task.payload = await buildPdf(report?.displayName ?? 'Report', [
      `Reference: ${task.reportReference}`,
      `Generated: ${new Date().toISOString()}`,
      '',
      'This is a mock PDF generated by qalipsis-webapp mock-server.',
      'Components and data are synthetic.',
    ])
  }
  res.type('application/pdf').send(task.payload)
})

reportsRouter.post('/:reference/render', (req, res) => {
  const report = db.reports.get(req.params.reference)
  if (!report) {
    res.status(404).json({ message: `Report ${req.params.reference} not found` })

    return
  }
  const taskRef = randomUUID()
  const nowIso = new Date().toISOString()
  db.reportTasks.set(taskRef, {
    reference: taskRef,
    reportReference: report.reference,
    readyAt: Date.now() + 1500,
    creationTimestamp: nowIso,
  })
  const task: ReportTask = {
    reference: taskRef,
    status: 'PENDING',
    creationTimestamp: nowIso,
    creator: 'qalipsis-dev',
  }
  res.json(task)
})

reportsRouter.get('/:reference', (req, res) => {
  const report = db.reports.get(req.params.reference)
  if (!report) {
    res.status(404).json({ message: `Report ${req.params.reference} not found` })

    return
  }
  res.json(report)
})

reportsRouter.put('/:reference', (req, res) => {
  const existing = db.reports.get(req.params.reference)
  if (!existing) {
    res.status(404).json({ message: `Report ${req.params.reference} not found` })

    return
  }
  const body = req.body as ReportCreationAndUpdateRequest
  const updated: DataReport = {
    ...existing,
    displayName: body.displayName ?? existing.displayName,
    description: body.description ?? existing.description,
    sharingMode: body.sharingMode ?? existing.sharingMode,
    campaignKeys: body.campaignKeys ?? existing.campaignKeys,
    campaignNamesPatterns: body.campaignNamesPatterns ?? existing.campaignNamesPatterns,
    scenarioNamesPatterns: body.scenarioNamesPatterns ?? existing.scenarioNamesPatterns,
    resolvedCampaigns: (body.campaignKeys ?? existing.campaignKeys ?? [])
      .map((k) => db.campaigns.get(k))
      .filter((c): c is NonNullable<typeof c> => !!c)
      .map((c) => ({ key: c.key, name: c.name })),
    dataComponents: body.dataComponents ? resolveComponents(body) : existing.dataComponents,
    version: new Date().toISOString(),
  }
  db.reports.set(req.params.reference, updated)
  res.json(updated)
})

// DELETE /reports?report=ref1,ref2
reportsRouter.delete('/', (req, res) => {
  const raw = req.query.report
  const refs = typeof raw === 'string' ? raw.split(',').map((r) => r.trim()).filter(Boolean) : []
  for (const r of refs) db.reports.delete(r)
  res.status(204).end()
})
