== Configuration

=== Starting QALIPSIS in different modes

Only few modes are supported for now, where head and factories are starting in the same instance of QALIPSIS.

==== Interactive

Execute QALIPSIS with the option `--prompt` or `-p` to be prompted to enter the main configuration:

.Starting QALIPSIS in interactive mode
[source,bash]
----
java -jar my-scenario-qalipsis.jar --prompt
----

You will be asked to enter the load factor, speed factor and so on.

==== Select the scenarios to execute

You can pass selectors for the scenarios to execute, using the option `--scenarios` or `-s`.
The value is a comma-separated list of exact values or patterns of the scenarios to include.
The pattern can contain the wildcards `*` to match zero or more signs or `?` to match exactly one sign.

.Select the scenarios to run
[source,bash]
----
java -jar my-scenario-qalipsis.jar --scenarios "my-first-scenario, ?y-*-s*n?rio"
----

=== Runtime configuration

==== Command-line arguments

.Number of minions by scenario
`campaign.minions-count-per-scenario`, integer, default is the number as described in <<Configuring a scenario specification>>.

Defines how many minions should be used in the load-injected tree.
No compliant with `campaign.minions-factor`.

.Load factor
`campaign.minions-factor`, double, default to 1

Multiplies the default number of minions of each scenario by the provided value.
Can be between 0 and 1 to reduce the default value.
No compliant with `campaign.minions-count-per-scenario`.

.Speed factor
`campaign.speed-factor`, double, default to 1

Applies on the ramp-up to accelerate or slow down the pace of the minions to be started.

All the command-line arguments can also be provided in a file, as explained in next section.

==== External property sources

QALIPSIS uses Micronaut's runtime underneath.
Hence, you can use its mechanism of https://docs.micronaut.io/latest/guide/index.html#propertySource[externalized configuration with property sources].

You can overwrite the default configuration and add your own properties creating a file `application-config.yml` either in the class path or in the working directory.

For your convenience, you can also specified additional environments using the parameter `--environments` (shorthand `-e`) and the required list:

[source,bash]
----
java -jar my-scenario-qalipsis.jar -e my-scenario,production
----

When doing such, the configuration files `application-my-scenario.{extension}` and `application-production.{extension}` will be applied, where `{extension}` can be `.properties`, `.json` or `.yml`.

=== Injecting configuration in a scenario

You can inject values into your scenario or its declaring class using the annotation `@io.qalipsis.api.annotations.Property`.

[source,kotlin]
----
class EcommercePurchase(@Property("ecommerce-purchase.load") private val numberOfMinions: Int) {

    @Scenario
    fun fromLoginToCheckout(@Property("ecommerce-purchase.action-pace") actionPaceDuration: Duration) {
        scenario("login-select-and-checkout"){
            minionsCount = numberOfMinions
        }
        .constantPace(actionPaceDuration.toMillis())
        // ...
    }
}
----
