import PDFDocument from 'pdfkit'

export const buildPdf = (title: string, body: string[]): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    doc.fontSize(20).text(title, { align: 'left' })
    doc.moveDown()
    doc.fontSize(11).fillColor('#555').text(`Generated by qalipsis-webapp mock-server — ${new Date().toISOString()}`)
    doc.moveDown()
    doc.fillColor('black').fontSize(12)
    for (const line of body) {
      doc.text(line)
      doc.moveDown(0.3)
    }
    doc.end()
  })
}
