datasource:
  host: localhost
  port: 5432
  database: qalipsis
  schema: qalipsis
  username: qalipsis
  password: qalipsis
  pool:
    min: 4
    max: 20
    maxLifeTime: PT10M
    maxIdleTime: PT4M
    maxAcquireTime: PT5S

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${datasource.host}:${datasource.port}/${datasource.database}
      username: ${datasource.username}
      password: ${datasource.password}
      schema-generate: none
      options:
        driver: pool
        protocol: postgres
        maxSize: ${datasource.pool.max}
        initialSize: ${datasource.pool.min}
        maxLifeTime: ${datasource.pool.maxLifeTime}
        maxIdleTime: ${datasource.pool.maxIdleTime}
        maxAcquireTime: ${datasource.pool.maxAcquireTime}
        poolName: r2dbc
        registerJmx: false
        validationQuery: select 1
        schema: ${datasource.schema}

liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'db/liquibase-changelog.xml'
      liquibase-schema: qalipsis_liquibase
