security:
  authentication: idtoken
  oauth2:
    clients:
      auth0:
        client-id: '${OAUTH_CLIENT_ID:xxx}'
        client-secret: '${OAUTH_CLIENT_SECRET:yyy}'
        openid:
          issuer: 'https://${OAUTH_DOMAIN:micronautguides.eu.auth0.com}/'
  endpoints:
    logout:
      get-allowed: true