identity:
  manager: auth0
  auth0:
    domain: "my-domain.auth0.com"
    json-web-key-set: 'https://${identity.auth0.domain}/.well-known/jwks.json'
    oauth2:
      roles: "https://qalipsis.io/roles"
      tenants: "https://qalipsis.io/tenants"
      client-id: "-"
      authorization-url: "https://${identity.auth0.domain}/authorize"
      revocation-url: "https://${identity.auth0.domain}/revoke"
    management:
      client-id: "-"
      client-secret: "-"
      connection: "Username-Password-Authentication"
      api-url: https://${identity.auth0.domain}/api/v2/
  bind-tenant: true

micronaut:
  security:
    enabled: true
    token:
      roles-name: "${identity.auth0.oauth2.roles}"
      name-key: sub
      jwt:
        enabled: true
        claims-validators:
          subject-not-null: false
          expiration: true
        signatures:
          jwks:
            auth0:
              url: ${identity.auth0.json-web-key-set}
