redis:
  uri: redis://localhost:6379
  #uris: # To use a cluster.
  # - redis://redis-1:6379
  # - redis://redis-2:6379
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  client-name: "head"

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver

liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'