datasource:
  host: localhost
  port: 5432
  database: qalipsis
  schema: qalipsis
  username: qalipsis
  password: qalipsis

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://${datasource.host}:${datasource.port}/${datasource.database}
      username: ${datasource.username}
      password: ${datasource.password}
      schema-generate: none
      options:
        driver: pool
        protocol: postgres
        maxSize: 20
        initialSize: 4
        maxLifeTime: PT5M
        maxIdleTime: PT4M
        maxAcquireTime: PT5S
        poolName: r2dbc
        registerJmx: false
        validationQuery: select 1
        schema: ${datasource.schema}

liquibase:
  enabled: true
  datasources:
    default:
      change-log: 'db/liquibase-changelog.xml'
      liquibase-schema: qalipsis_liquibase
