identity:
  manager: auth0
  auth0:
    client-id: QddokR3NNMzECAu2Ww5yVLzNcqTuWIWV
    client-secret: yk4sV_HULJdYCQ4wUvmhP6sTD9ocNXMCeNKhfetEJQYTep_MeXFQrvpfHxCCPYh4
    api-identifier: https://dev-d7xe49-1.us.auth0.com/api/v2/
    domain: dev-d7xe49-1.us.auth0.com