name: Build and publish QALIPSIS Web OSS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  GITHUB_ACTIONS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Login to QALIPSIS private registry
        uses: docker/login-action@v2
        with:
          registry: zakd79ka.gra7.container-registry.ovh.net
          username: ${{ secrets.PROPRIETARY_DOCKER_USERNAME }}
          password: ${{ secrets.PROPRIETARY_DOCKER_PASSWORD }}

      - name: Build and publish
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: ./gradlew buildDocker dockerPush
