name: Java CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        java: ['11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1 # https://github.com/actions/setup-java
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-evolue-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-evolue-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-evolue-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-evolue-gradle-wrapper-

      - name: Unit tests
        run: ./gradlew --no-daemon --parallel --continue --info clean test

      - name: Integration tests
        run: ./gradlew --no-daemon --parallel --continue --info integrationTest
